# Generated by Django 5.0.4 on 2024-05-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrip',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
