# Generated by Django 5.0.4 on 2024-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_plantrip_endtime_alter_plantrip_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='statc/images/'),
        ),
    ]
