# Generated by Django 5.0.4 on 2024-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_tourguide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
